In [5]:
import numpy as np

# Create a rank 1 array
data = np.array([1, 2, 3, 4])
print(data.ndim)
print(data.shape)

# Create a rank 2 array
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(data.ndim)
print(data.shape)

1
(4,)
2
(2, 4)


In [6]:
# zeros
data = np.zeros((2, 3))
print(data)
np.array([[0., 0., 0.], [0., 0., 0.]])

# ones
data = np.ones(4)
print(data)

[[0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
data = np.ones((2, 3))
print(data.dtype)
data = np.ones((2, 3), dtype=np.int64)
print(data.dtype)

float64
int64


In [9]:
x1 = 5.4 * np.ones(10) 
x2 = np.full(10,5.4)

In [11]:
x1 = np.empty(5)
x1.fill(3.0)
print(x1)
x2 = np.full(5, 3.0)
print(x2)

[3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3.]


In [14]:
x1 = np.arange(0.0, 10, 1)
print(x1)
np.linspace(0, 10, 11)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
x1 = np.logspace(0, 2, 5) # 5 data points from 10^0 to 10^2
print(x1)

[  1.           3.16227766  10.          31.6227766  100.        ]


In [18]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
[[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]
