In [29]:
import numpy as np
import scipy.stats as stats

In [30]:
npoints = 20   # number of integer support points of the distribution minus 1
npointsh = npoints // 2
npointsf = float(npoints)
nbound = 4   # bounds for the truncated normal
normbound = (1+1/npointsf) * nbound   # actual bounds of truncated normal

In [31]:
grid = np.arange(-npointsh, npointsh+2, 1)   # integer grid
print(grid)
gridlimitsnorm = (grid-0.5) / npointsh * nbound   # bin limits for the truncnorm
print(gridlimitsnorm)
gridlimits = grid - 0.5   # used later in the analysis
print(gridlimits)
grid = grid[:-1]  # remove last point

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10  11]
[-4.2 -3.8 -3.4 -3.  -2.6 -2.2 -1.8 -1.4 -1.  -0.6 -0.2  0.2  0.6  1.
  1.4  1.8  2.2  2.6  3.   3.4  3.8  4.2]
[-10.5  -9.5  -8.5  -7.5  -6.5  -5.5  -4.5  -3.5  -2.5  -1.5  -0.5   0.5
   1.5   2.5   3.5   4.5   5.5   6.5   7.5   8.5   9.5  10.5]


In [32]:
probs = np.diff(stats.truncnorm.cdf(gridlimitsnorm, -normbound, normbound)) # derivative of the cdf of the truncated normal is the pdf
gridint = grid.astype(int)  # integer grid

In [33]:
normdiscrete = stats.rv_discrete(values=(gridint, np.round(probs, decimals=7)), name='normdiscrete')  # discrete distribution for the truncated normal
print('mean = %6.4f, variance = %6.4f, skew = %6.4f, kurtosis = %6.4f' %
      normdiscrete.stats(moments='mvsk')) # print mean, variance, skewness and kurtosis of the truncated normal distribution 

mean = -0.0000, variance = 6.3302, skew = 0.0000, kurtosis = -0.0076


In [34]:
nd_std = np.sqrt(normdiscrete.stats(moments='v'))  # standard deviation, sqrt(variance)

In [35]:
n_sample = 500
rvs = normdiscrete.rvs(size=n_sample) # random sample from the truncated normal distribution
f, l = np.histogram(rvs, bins=gridlimits) # histogram of the random sample
sfreq = np.vstack([gridint, f, probs*n_sample]).T  # table of the sample frequencies and the expected frequencies
print(sfreq)

[[-1.00000000e+01  0.00000000e+00  2.95019349e-02]
 [-9.00000000e+00  0.00000000e+00  1.32294142e-01]
 [-8.00000000e+00  0.00000000e+00  5.06497902e-01]
 [-7.00000000e+00  0.00000000e+00  1.65568919e+00]
 [-6.00000000e+00  5.00000000e+00  4.62125309e+00]
 [-5.00000000e+00  1.10000000e+01  1.10137298e+01]
 [-4.00000000e+00  2.90000000e+01  2.24137683e+01]
 [-3.00000000e+00  5.20000000e+01  3.89503370e+01]
 [-2.00000000e+00  4.90000000e+01  5.78004747e+01]
 [-1.00000000e+00  7.30000000e+01  7.32455414e+01]
 [ 0.00000000e+00  7.60000000e+01  7.92618251e+01]
 [ 1.00000000e+00  7.80000000e+01  7.32455414e+01]
 [ 2.00000000e+00  4.50000000e+01  5.78004747e+01]
 [ 3.00000000e+00  4.20000000e+01  3.89503370e+01]
 [ 4.00000000e+00  2.10000000e+01  2.24137683e+01]
 [ 5.00000000e+00  1.30000000e+01  1.10137298e+01]
 [ 6.00000000e+00  3.00000000e+00  4.62125309e+00]
 [ 7.00000000e+00  2.00000000e+00  1.65568919e+00]
 [ 8.00000000e+00  1.00000000e+00  5.06497902e-01]
 [ 9.00000000e+00  0.00000000e+

In [36]:
f2 = np.hstack([f[:5].sum(), f[5:-5], f[-5:].sum()]) # first and last 5 bins are combined
p2 = np.hstack([probs[:5].sum(), probs[5:-5], probs[-5:].sum()]) # first and last 5 bins are combined
ch2, pval = stats.chisquare(f2, p2*n_sample) # chi-square test of the random sample against the truncated normal distribution 

In [37]:
print('chisquare for normdiscrete: chi2 = %6.3f pvalue = %6.4f' % (ch2, pval))

chisquare for normdiscrete: chi2 = 12.285 pvalue = 0.4230
